SELECT c.CAR_ID, c.CAR_TYPE, FLOOR((30*c.DAILY_FEE)*(1-p.DISCOUNT_RATE/100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR c
JOIN
(SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE DURATION_TYPE='30일 이상') p
ON c.CAR_TYPE=p.CAR_TYPE
JOIN
(SELECT CAR_ID, COUNT(
    CASE 
        WHEN (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01') THEN NULL
        ELSE 1
    END
) as temp
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 GROUP BY CAR_ID HAVING temp=0) h
ON c.CAR_ID=h.CAR_ID
WHERE c.CAR_TYPE IN ('세단', 'SUV') AND
(30*c.DAILY_FEE)*(1-p.DISCOUNT_RATE/100) >= 500000 AND
(30*c.DAILY_FEE)*(1-p.DISCOUNT_RATE/100) < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;
