WITH TEMP AS (
    SELECT b.HISTORY_ID, a.CAR_TYPE, a.DAILY_FEE, DATEDIFF(b.END_DATE, b.START_DATE) + 1 as DURATION
    FROM (SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE='트럭') a
    JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY b
    USING(CAR_ID)
)

SELECT a.HISTORY_ID, FLOOR((a.DURATION*a.DAILY_FEE) * (1 - IFNULL(b.DISCOUNT_RATE, 0) / 100)) as FEE
FROM TEMP a LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
ON a.CAR_TYPE=b.CAR_TYPE AND ((b.DURATION_TYPE='7일 이상' AND a.DURATION >= 7 AND a.DURATION < 30) OR
(b.DURATION_TYPE='30일 이상' AND a.DURATION >= 30 AND a.DURATION < 90) OR
(b.DURATION_TYPE='90일 이상' AND a.DURATION >= 90))
ORDER BY FEE DESC, HISTORY_ID DESC