# SELECT FLAVOR
# FROM (SELECT a.FLAVOR, SUM(
#     CASE
#         WHEN a.SHIPMENT_ID=b.SHIPMENT_ID THEN a.TOTAL_ORDER+b.TOTAL_ORDER
#         ELSE b.TOTAL_ORDER
#     END
# )
# as TOTAL_ORDER
# FROM FIRST_HALF a JOIN JULY b
# ON a.FLAVOR=b.FLAVOR
# GROUP BY FLAVOR
# ORDER BY TOTAL_ORDER DESC LIMIT 3) c

WITH JULY_F AS (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
               FROM JULY GROUP BY FLAVOR)

SELECT A.FLAVOR
FROM (SELECT FH.FLAVOR, FH.TOTAL_ORDER + COALESCE(J.TOTAL_ORDER, 0) AS TOTAL FROM FIRST_HALF FH
LEFT JOIN JULY_F J ON FH.FLAVOR = J.FLAVOR) A
ORDER BY A.TOTAL DESC
LIMIT 3