SELECT FLAVOR
FROM (SELECT a.FLAVOR, SUM(
    CASE
        WHEN a.SHIPMENT_ID=b.SHIPMENT_ID THEN a.TOTAL_ORDER+b.TOTAL_ORDER
        ELSE b.TOTAL_ORDER
    END
)
as TOTAL_ORDER
FROM FIRST_HALF a JOIN JULY b
ON a.FLAVOR=b.FLAVOR
GROUP BY FLAVOR
ORDER BY TOTAL_ORDER DESC LIMIT 3) c