-- 코드를 입력하세요
WITH TOP_REVIEWER AS (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_COUNT FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY REVIEW_COUNT DESC)
 
SELECT a.MEMBER_NAME, b.REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE a JOIN REST_REVIEW b
ON a.MEMBER_ID=b.MEMBER_ID
WHERE a.MEMBER_ID IN (SELECT MEMBER_ID FROM TOP_REVIEWER WHERE REVIEW_COUNT=(SELECT REVIEW_COUNT FROM TOP_REVIEWER LIMIT 1))
ORDER BY 3, 2