-- 코드를 입력하세요
WITH TOP_REVIEWER AS (SELECT MEMBER_ID, COUNT(MEMBER_ID) AS REVIEW_COUNT FROM REST_REVIEW GROUP BY MEMBER_ID)
 
SELECT a.MEMBER_NAME, b.REVIEW_TEXT, DATE_FORMAT(b.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE a JOIN REST_REVIEW b
ON a.MEMBER_ID=b.MEMBER_ID
WHERE a.MEMBER_ID IN (SELECT MEMBER_ID FROM (SELECT MEMBER_ID, RANK() OVER(ORDER BY REVIEW_COUNT DESC) as RNK FROM TOP_REVIEWER) as c WHERE RNK=1)
ORDER BY 3, 2