SELECT a.CATEGORY, SUM(b.TOTAL_SALES) as TOTAL_SALES
FROM BOOK a
    JOIN
    (SELECT BOOK_ID, SUM(SALES) as TOTAL_SALES FROM BOOK_SALES WHERE SUBSTR(SALES_DATE, 1, 7)='2022-01' GROUP BY BOOK_ID) b
    USING(BOOK_ID)
GROUP BY a.CATEGORY
ORDER BY 1
